#!/bin/sh
cd ..
python3 -c "from pylyttlebit.lb_branch import LbBranch; LbBranch().hello_world()"
python3 -c "from pylyttlebit.lb_constants import LbConstants; LbConstants().hello_world()"
python3 -c "from pylyttlebit.lb_dev_env import LbDevEnv; LbDevEnv().hello_world()"
python3 -c "from pylyttlebit.lb_doc_comments import LbDocComments; LbDocComments().hello_world()"
python3 -c "from pylyttlebit.lb_doc_folders import LbDocFolders; LbDocFolders().hello_world()"
python3 -c "from pylyttlebit.lb_folders import LbFolders; LbFolders().hello_world()"
python3 -c "from pylyttlebit.lb_project import LbProject; LbProject().hello_world()"
python3 -c "from pylyttlebit.lb_recorder import LbRecorder; LbRecorder().hello_world()"
python3 -c "from pylyttlebit.lb_step import LbStep; LbStep().hello_world()"
python3 -c "from pylyttlebit.lb_step_list import LbStepList; LbStepList().hello_world()"
python3 -c "from pylyttlebit.lb_text_file import LbTextFile; LbTextFile().hello_world()"
python3 -c "from pylyttlebit.lb_text_file_helper import LbTextFileHelper; LbTextFileHelper().hello_world()"
python3 -c "from pylyttlebit.lb_util import LbUtil; LbUtil().hello_world()"
